"use client";

import { useEffect, useMemo, useState } from "react";
import { formatMoney, type Invoice, type InvoiceStatus } from "../lib/domain";

const label: Record<InvoiceStatus, string> = { overdue: "Overdue", due_soon: "Due soon", paid: "Paid" };

export default function Home() {
  const [invoices, setInvoices] = useState<Invoice[]>([]), [loading, setLoading] = useState(true), [error, setError] = useState("");
  const [customer, setCustomer] = useState(""), [email, setEmail] = useState(""), [amount, setAmount] = useState(""), [due, setDue] = useState("");
  const [filter, setFilter] = useState<"all" | InvoiceStatus>("all"), [reminder, setReminder] = useState("Choose an invoice to preview a professional follow-up message.");

  async function loadInvoices() { setLoading(true); try { const r = await fetch("/api/invoices"); const data = await r.json(); if (r.status === 401) { window.location.href = "/login"; return; } if (!r.ok) throw new Error(data.error); setInvoices(data.invoices ?? []); setError(""); } catch { setInvoices([]); setError("Could not load your invoices."); } finally { setLoading(false); } }
  useEffect(() => { void loadInvoices(); }, []);

  const totals = useMemo(() => ({ outstanding: invoices.filter(i=>i.status!=="paid").reduce((a,i)=>a+i.amount,0), overdue: invoices.filter(i=>i.status==="overdue").reduce((a,i)=>a+i.amount,0), paid: invoices.filter(i=>i.status==="paid").reduce((a,i)=>a+i.amount,0) }), [invoices]);
  const visible = filter === "all" ? invoices : invoices.filter(i=>i.status===filter);

  async function addInvoice(e: React.FormEvent) { e.preventDefault(); if (!customer.trim()||!email.trim()||!amount||!due||Number(amount)<=0) return; setError(""); try { const r=await fetch("/api/invoices",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({customerName:customer,customerEmail:email,amount:Number(amount),dueDate:due,currency:"USD"})}); const data=await r.json(); if(!r.ok) throw new Error(data.error); setInvoices(prev=>[data.invoice,...prev]); setCustomer("");setEmail("");setAmount("");setDue(""); } catch { setError("Could not create the invoice. Please try again."); } }
  async function generate(i: Invoice) { try { const r=await fetch("/api/reminder",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({invoiceId:i.id})}); const data=await r.json(); if(!r.ok) throw new Error(data.error); setReminder(data.message); } catch { setError("Could not generate the reminder."); } }
  async function changeStatus(id:string,status:InvoiceStatus) { const r=await fetch(`/api/invoices/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status})}); if(r.ok) setInvoices(prev=>prev.map(i=>i.id===id?{...i,status}:i)); else setError("Could not update the invoice."); }
  async function remove(id:string) { const r=await fetch(`/api/invoices/${id}`,{method:"DELETE"}); if(r.ok) setInvoices(prev=>prev.filter(i=>i.id!==id)); else setError("Could not delete the invoice."); }

  return <div className="shell"><header className="topbar"><div className="brand"><span className="logo">IP</span> InvoicePilot <span className="badge">MVP</span></div><span className="muted">Invoice follow-up, simplified.</span></header><main className="main">
    <section className="hero"><div><h1>Good afternoon 👋</h1><p className="muted">Keep cash moving without chasing every invoice.</p></div><button className="primary" onClick={()=>document.getElementById("new-invoice")?.scrollIntoView({behavior:"smooth"})}>+ New invoice</button></section>
    {error && <div className="notice">{error}</div>}
    <section className="grid"><div className="card"><div className="stat-label">Outstanding</div><div className="stat-value">{formatMoney(totals.outstanding)}</div></div><div className="card"><div className="stat-label">Overdue</div><div className="stat-value">{formatMoney(totals.overdue)}</div></div><div className="card"><div className="stat-label">Paid</div><div className="stat-value">{formatMoney(totals.paid)}</div></div><div className="card"><div className="stat-label">Active invoices</div><div className="stat-value">{invoices.filter(i=>i.status!=="paid").length}</div></div></section>
    <section className="layout"><div className="card"><div className="card-head"><span className="card-title">Invoices</span><select className="filter" value={filter} onChange={e=>setFilter(e.target.value as "all"|InvoiceStatus)}><option value="all">All</option><option value="overdue">Overdue</option><option value="due_soon">Due soon</option><option value="paid">Paid</option></select></div><div className="table-wrap"><table className="table"><thead><tr><th>Customer</th><th>Invoice</th><th>Amount</th><th>Due</th><th>Status</th><th>Actions</th></tr></thead><tbody>{loading ? <tr><td colSpan={6}>Loading invoices…</td></tr> : visible.map(i=><tr key={i.id}><td><strong>{i.customerName}</strong><small>{i.customerEmail}</small></td><td>{i.invoiceNumber}</td><td>{formatMoney(i.amount,i.currency)}</td><td>{i.dueDate}</td><td><span className={`status ${i.status}`}>{label[i.status]}</span></td><td><div className="actions"><button className="link-btn" onClick={()=>generate(i)}>Remind</button><select className="mini-select" value={i.status} onChange={e=>void changeStatus(i.id,e.target.value as InvoiceStatus)}><option value="overdue">Overdue</option><option value="due_soon">Due soon</option><option value="paid">Paid</option></select><button className="delete-btn" aria-label={`Delete ${i.invoiceNumber}`} onClick={()=>void remove(i.id)}>×</button></div></td></tr>)}</tbody></table></div></div>
    <div className="card" id="new-invoice"><div className="card-head"><span className="card-title">Add invoice</span></div><form className="form" onSubmit={addInvoice}><label>Customer<input value={customer} onChange={e=>setCustomer(e.target.value)} placeholder="Acme Studio" required/></label><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="billing@acme.com" required/></label><label>Amount<input type="number" min="0.01" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="1250" required/></label><label>Due date<input type="date" value={due} onChange={e=>setDue(e.target.value)} required/></label><button className="primary" type="submit">Create invoice</button></form><div className="preview"><div className="card-title">Reminder preview</div><div className="reminder">{reminder}</div><p className="hint">Generated securely through the server API.</p></div></div></section>
  </main></div>;
}
