"use client";

import { useEffect, useMemo, useState } from "react";
import { formatMoney, reminderFor, type Invoice, type InvoiceStatus } from "../lib/domain";
import { createInvoice, deleteInvoice, updateInvoiceStatus } from "../lib/invoice-service";

const seed: Invoice[] = [
  { id: "1", customerName: "Northstar Studio", customerEmail: "billing@northstar.test", invoiceNumber: "INV-1042", amount: 1250, currency: "USD", dueDate: "2026-08-26", status: "overdue", createdAt: "2026-08-01" },
  { id: "2", customerName: "Maya Consulting", customerEmail: "maya@example.test", invoiceNumber: "INV-1043", amount: 780, currency: "USD", dueDate: "2026-08-30", status: "due_soon", createdAt: "2026-08-02" },
  { id: "3", customerName: "Atlas Repairs", customerEmail: "accounts@atlas.test", invoiceNumber: "INV-1041", amount: 420, currency: "USD", dueDate: "2026-08-18", status: "paid", createdAt: "2026-07-20" },
];
const label: Record<InvoiceStatus, string> = { overdue: "Overdue", due_soon: "Due soon", paid: "Paid" };

export default function Home() {
  const [invoices, setInvoices] = useState<Invoice[]>([]), [loading, setLoading] = useState(true), [error, setError] = useState("");
  const [customer, setCustomer] = useState(""), [email, setEmail] = useState(""), [amount, setAmount] = useState(""), [due, setDue] = useState("");
  const [filter, setFilter] = useState<"all" | InvoiceStatus>("all"), [reminder, setReminder] = useState("Choose an invoice to preview a professional follow-up message.");

  useEffect(() => { fetch("/api/invoices").then(r => r.ok ? r.json() : Promise.reject(new Error("Could not load invoices"))).then(data => setInvoices(data.invoices ?? seed)).catch(() => { setInvoices(seed); setError("API unavailable — showing demo data."); }).finally(() => setLoading(false)); }, []);
  const totals = useMemo(() => ({ outstanding: invoices.filter(i=>i.status!=="paid").reduce((a,i)=>a+i.amount,0), overdue: invoices.filter(i=>i.status==="overdue").reduce((a,i)=>a+i.amount,0), paid: invoices.filter(i=>i.status==="paid").reduce((a,i)=>a+i.amount,0) }), [invoices]);
  const visible = filter === "all" ? invoices : invoices.filter(i=>i.status===filter);

  async function addInvoice(e: React.FormEvent) { e.preventDefault(); if (!customer.trim()||!email.trim()||!amount||!due||Number(amount)<=0) return; setError(""); try { const r=await fetch("/api/invoices",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({customerName:customer,customerEmail:email,amount:Number(amount),dueDate:due,currency:"USD"})}); const data=await r.json(); if(!r.ok) throw new Error(data.error||"Unable to create invoice"); setInvoices(prev=>[data.invoice,...prev]); setCustomer("");setEmail("");setAmount("");setDue(""); } catch { setError("Could not create the invoice. Please try again."); } }
  async function generate(i: Invoice) { try { const r=await fetch("/api/reminder",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({invoice:i})}); const data=await r.json(); if(!r.ok) throw new Error(); setReminder(data.message); } catch { setReminder(reminderFor(i)); } }
  function localStatus(id:string,status:InvoiceStatus){ setInvoices(prev=>updateInvoiceStatus(prev,id,status)); }

  return <div className="shell"><header className="topbar"><div className="brand"><span className="logo">IP</span> InvoicePilot <span className="badge">MVP</span></div><span className="muted">Invoice follow-up, simplified.</span></header><main className="main">
    <section className="hero"><div><h1>Good afternoon 👋</h1><p className="muted">Keep cash moving without chasing every invoice.</p></div><button className="primary" onClick={()=>document.getElementById("new-invoice")?.scrollIntoView({behavior:"smooth"})}>+ New invoice</button></section>
    {error && <div className="notice">{error}</div>}
    <section className="grid"><div className="card"><div className="stat-label">Outstanding</div><div className="stat-value">{formatMoney(totals.outstanding)}</div></div><div className="card"><div className="stat-label">Overdue</div><div className="stat-value">{formatMoney(totals.overdue)}</div></div><div className="card"><div className="stat-label">Paid</div><div className="stat-value">{formatMoney(totals.paid)}</div></div><div className="card"><div className="stat-label">Active invoices</div><div className="stat-value">{invoices.filter(i=>i.status!=="paid").length}</div></div></section>
    <section className="layout"><div className="card"><div className="card-head"><span className="card-title">Invoices</span><select className="filter" value={filter} onChange={e=>setFilter(e.target.value as "all"|InvoiceStatus)}><option value="all">All</option><option value="overdue">Overdue</option><option value="due_soon">Due soon</option><option value="paid">Paid</option></select></div><div className="table-wrap"><table className="table"><thead><tr><th>Customer</th><th>Invoice</th><th>Amount</th><th>Due</th><th>Status</th><th>Actions</th></tr></thead><tbody>{loading ? <tr><td colSpan={6}>Loading invoices…</td></tr> : visible.map(i=><tr key={i.id}><td><strong>{i.customerName}</strong><small>{i.customerEmail}</small></td><td>{i.invoiceNumber}</td><td>{formatMoney(i.amount,i.currency)}</td><td>{i.dueDate}</td><td><span className={`status ${i.status}`}>{label[i.status]}</span></td><td><div className="actions"><button className="link-btn" onClick={()=>generate(i)}>Remind</button><select className="mini-select" value={i.status} onChange={e=>localStatus(i.id,e.target.value as InvoiceStatus)}><option value="overdue">Overdue</option><option value="due_soon">Due soon</option><option value="paid">Paid</option></select><button className="delete-btn" aria-label={`Delete ${i.invoiceNumber}`} onClick={()=>setInvoices(prev=>deleteInvoice(prev,i.id))}>×</button></div></td></tr>)}</tbody></table></div></div>
    <div className="card" id="new-invoice"><div className="card-head"><span className="card-title">Add invoice</span></div><form className="form" onSubmit={addInvoice}><label>Customer<input value={customer} onChange={e=>setCustomer(e.target.value)} placeholder="Acme Studio" required/></label><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="billing@acme.com" required/></label><label>Amount<input type="number" min="0.01" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="1250" required/></label><label>Due date<input type="date" value={due} onChange={e=>setDue(e.target.value)} required/></label><button className="primary" type="submit">Create invoice</button></form><div className="preview"><div className="card-title">Reminder preview</div><div className="reminder">{reminder}</div><p className="hint">Reminder generation now uses the server API.</p></div></div></section>
  </main></div>;
}
