"use client";

import { useEffect, useMemo, useState } from "react";
import { formatMoney, type Invoice, type InvoiceStatus } from "../lib/domain";

type Billing = { plan: "free" | "pro" | "business"; status: string; invoiceLimit: number | null; reminderLimit: number | null; automaticReminders: boolean; monthlyPriceCents: number };
const label: Record<InvoiceStatus, string> = { overdue: "Overdue", due_soon: "Due soon", paid: "Paid" };
const planName = (p: Billing["plan"]) => p[0].toUpperCase() + p.slice(1);

export default function Home() {
  const [invoices, setInvoices] = useState<Invoice[]>([]), [billing, setBilling] = useState<Billing | null>(null), [loading, setLoading] = useState(true), [error, setError] = useState(""), [sending, setSending] = useState<string | null>(null), [upgradePlan, setUpgradePlan] = useState<"pro"|"business"|null>(null);
  const [customer, setCustomer] = useState(""), [email, setEmail] = useState(""), [amount, setAmount] = useState(""), [due, setDue] = useState("");
  const [filter, setFilter] = useState<"all" | InvoiceStatus>("all"), [reminder, setReminder] = useState("Choose an invoice to preview a professional follow-up message.");

  async function load() { setLoading(true); try { const [ir, br] = await Promise.all([fetch("/api/invoices"), fetch("/api/billing")]); const id = await ir.json(); const bd = await br.json(); if (ir.status === 401 || br.status === 401) { window.location.href = "/login"; return; } if (!ir.ok) throw new Error(id.error); setInvoices(id.invoices ?? []); if (br.ok) setBilling(bd.subscription); setError(""); } catch { setInvoices([]); setError("Could not load your workspace."); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, []);
  const totals = useMemo(() => ({ outstanding: invoices.filter(i=>i.status!=="paid").reduce((a,i)=>a+i.amount,0), overdue: invoices.filter(i=>i.status==="overdue").reduce((a,i)=>a+i.amount,0), paid: invoices.filter(i=>i.status==="paid").reduce((a,i)=>a+i.amount,0) }), [invoices]);
  const visible = filter === "all" ? invoices : invoices.filter(i=>i.status===filter);
  const invoiceUsage = billing?.invoiceLimit === null ? `${invoices.length} used` : `${invoices.length} / ${billing?.invoiceLimit ?? "—"}`;

  async function addInvoice(e: React.FormEvent) { e.preventDefault(); if (!customer.trim()||!email.trim()||!amount||!due||Number(amount)<=0) return; setError(""); try { const r=await fetch("/api/invoices",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({customerName:customer,customerEmail:email,amount:Number(amount),dueDate:due,currency:"USD"})}); const data=await r.json(); if(!r.ok) throw new Error(data.error); setInvoices(prev=>[data.invoice,...prev]); setCustomer("");setEmail("");setAmount("");setDue(""); } catch (e) { setError(e instanceof Error ? e.message : "Could not create the invoice."); } }
  async function generate(i: Invoice) { setError(""); try { const r=await fetch("/api/reminder",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({invoiceId:i.id})}); const data=await r.json(); if(!r.ok) throw new Error(data.error); setReminder(data.message); } catch { setError("Could not generate the reminder."); } }
  async function sendReminder(i: Invoice) { setSending(i.id); setError(""); try { const r=await fetch("/api/reminder/send",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({invoiceId:i.id})}); const data=await r.json(); if(!r.ok) throw new Error(data.error); setReminder(`Reminder sent to ${i.customerEmail}.`); } catch { setError("Could not send the reminder. Check your plan and email provider configuration."); } finally { setSending(null); } }
  async function changeStatus(id:string,status:InvoiceStatus) { const r=await fetch(`/api/invoices/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status})}); if(r.ok) setInvoices(prev=>prev.map(i=>i.id===id?{...i,status}:i)); else setError("Could not update the invoice."); }
  async function remove(id:string) { const r=await fetch(`/api/invoices/${id}`,{method:"DELETE"}); if(r.ok) setInvoices(prev=>prev.filter(i=>i.id!==id)); else setError("Could not delete the invoice."); }
  async function logout() { await fetch("/api/auth/logout",{method:"POST"}); window.location.href="/login"; }
  async function upgrade(plan:"pro"|"business") { setUpgradePlan(plan); setError(""); try { const r=await fetch("/api/billing/checkout",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({plan})}); const data=await r.json(); if(!r.ok) throw new Error(data.error||"Checkout is not available yet."); if(data.checkoutUrl) window.location.href=data.checkoutUrl; } catch(e) { setError(e instanceof Error?e.message:"Could not start checkout."); setUpgradePlan(null); } }

  return <div className="shell"><header className="topbar"><div className="brand"><span className="logo">IP</span> InvoicePilot</div><div className="top-actions">{billing && <span className="plan-pill">{planName(billing.plan)} · {invoiceUsage} invoices</span>}<button className="link-btn" onClick={()=>void logout()}>Log out</button></div></header><main className="main">
    <section className="hero"><div><h1>Good afternoon 👋</h1><p className="muted">Keep cash moving without chasing every invoice.</p></div><button className="primary" onClick={()=>document.getElementById("new-invoice")?.scrollIntoView({behavior:"smooth"})}>+ New invoice</button></section>
    {billing && <section className="billing-card"><div><div className="eyebrow">CURRENT PLAN</div><h2>{planName(billing.plan)} {billing.monthlyPriceCents > 0 && <span className="price">${(billing.monthlyPriceCents/100).toFixed(0)}/mo</span>}</h2><p>{billing.invoiceLimit === null ? "Unlimited invoices" : `${invoices.length} of ${billing.invoiceLimit} invoices used`} · {billing.automaticReminders ? "Automatic reminders enabled" : "Automatic reminders not included"}</p></div><button className="secondary" onClick={()=>document.getElementById("pricing")?.scrollIntoView({behavior:"smooth"})}>{billing.plan === "business" ? "Current plan" : "View plans"}</button></section>}
    {error && <div className="notice">{error}</div>}
    <section className="grid"><div className="card"><div className="stat-label">Outstanding</div><div className="stat-value">{formatMoney(totals.outstanding)}</div></div><div className="card"><div className="stat-label">Overdue</div><div className="stat-value">{formatMoney(totals.overdue)}</div></div><div className="card"><div className="stat-label">Paid</div><div className="stat-value">{formatMoney(totals.paid)}</div></div><div className="card"><div className="stat-label">Active invoices</div><div className="stat-value">{invoices.filter(i=>i.status!=="paid").length}</div></div></section>
    <section className="layout"><div className="card"><div className="card-head"><span className="card-title">Invoices</span><select className="filter" value={filter} onChange={e=>setFilter(e.target.value as "all"|InvoiceStatus)}><option value="all">All</option><option value="overdue">Overdue</option><option value="due_soon">Due soon</option><option value="paid">Paid</option></select></div><div className="table-wrap"><table className="table"><thead><tr><th>Customer</th><th>Invoice</th><th>Amount</th><th>Due</th><th>Status</th><th>Actions</th></tr></thead><tbody>{loading ? <tr><td colSpan={6}>Loading invoices…</td></tr> : visible.map(i=><tr key={i.id}><td><strong>{i.customerName}</strong><small>{i.customerEmail}</small></td><td>{i.invoiceNumber}</td><td>{formatMoney(i.amount,i.currency)}</td><td>{i.dueDate}</td><td><span className={`status ${i.status}`}>{label[i.status]}</span></td><td><div className="actions"><button className="link-btn" onClick={()=>void generate(i)}>Preview</button><button className="link-btn" disabled={sending===i.id} onClick={()=>void sendReminder(i)}>{sending===i.id?"Sending…":"Send"}</button><select className="mini-select" value={i.status} onChange={e=>void changeStatus(i.id,e.target.value as InvoiceStatus)}><option value="overdue">Overdue</option><option value="due_soon">Due soon</option><option value="paid">Paid</option></select><button className="delete-btn" aria-label={`Delete ${i.invoiceNumber}`} onClick={()=>void remove(i.id)}>×</button></div></td></tr>)}</tbody></table></div></div>
    <div className="card" id="new-invoice"><div className="card-head"><span className="card-title">Add invoice</span></div><form className="form" onSubmit={addInvoice}><label>Customer<input value={customer} onChange={e=>setCustomer(e.target.value)} placeholder="Acme Studio" required/></label><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="billing@acme.com" required/></label><label>Amount<input type="number" min="0.01" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="1250" required/></label><label>Due date<input type="date" value={due} onChange={e=>setDue(e.target.value)} required/></label><button className="primary" type="submit">Create invoice</button></form><div className="preview"><div className="card-title">Reminder preview</div><div className="reminder">{reminder}</div><p className="hint">Generated securely through the server API.</p></div></div></section>
    <section className="pricing" id="pricing"><div className="section-title"><div><div className="eyebrow">PLANS</div><h2>Choose the plan that fits your workflow</h2></div><span className="hint">External payment links will open securely.</span></div><div className="pricing-grid"><Plan name="Free" price="$0" features={["5 invoices","5 sent reminders","Manual reminders"]} current={billing?.plan==="free"} onUpgrade={()=>{}} busy={false}/><Plan name="Pro" price="$9/mo" features={["100 invoices","100 sent reminders","Automatic reminders"]} current={billing?.plan==="pro"} onUpgrade={()=>void upgrade("pro")} busy={upgradePlan==="pro"}/><Plan name="Business" price="$19/mo" features={["Unlimited invoices","Unlimited reminders","Automatic reminders","Priority support"]} current={billing?.plan==="business"} onUpgrade={()=>void upgrade("business")} busy={upgradePlan==="business"}/></div></section>
  </main></div>;
}
function Plan({name,price,features,current,onUpgrade,busy}:{name:string;price:string;features:string[];current:boolean;onUpgrade:()=>void;busy:boolean}) { return <div className={`plan-card ${current?"current":""}`}><div className="plan-head"><h3>{name}</h3>{current&&<span className="current-badge">Current</span>}</div><div className="plan-price">{price}</div><ul>{features.map(f=><li key={f}>✓ {f}</li>)}</ul><button className={current?"secondary":"primary"} disabled={current||busy} onClick={onUpgrade}>{current?"Current plan":busy?"Opening checkout…":"Upgrade"}</button></div> }
