"use client";

import { useState } from "react";

export default function LoginPage() {
  const [email,setEmail]=useState(""),[password,setPassword]=useState(""),[name,setName]=useState(""),[registerMode,setRegisterMode]=useState(false),[error,setError]=useState(""),[busy,setBusy]=useState(false);
  async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");try{const url=registerMode?"/api/auth/register":"/api/auth/login";const body=registerMode?{email,name,password}:{email,password};const r=await fetch(url,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw new Error(data.error||"Request failed");if(registerMode){setRegisterMode(false);setName("");setPassword("");setError("Account created. Sign in to continue.");}else window.location.href="/";}catch(err){setError(err instanceof Error?err.message:"Unable to continue.");}finally{setBusy(false)}}
  return <main className="auth-shell"><div className="auth-card"><div className="brand"><span className="logo">IP</span> InvoicePilot</div><h1>{registerMode?"Create your account":"Welcome back"}</h1><p className="muted">{registerMode?"Start managing your invoices securely.":"Sign in to access your invoices."}</p><form className="form" onSubmit={submit}>{registerMode&&<label>Name<input value={name} onChange={e=>setName(e.target.value)} minLength={2} required/></label>}<label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} minLength={8} required/></label>{error&&<div className="notice">{error}</div>}<button className="primary" disabled={busy}>{busy?"Please wait…":registerMode?"Create account":"Sign in"}</button></form><button className="link-btn" onClick={()=>{setRegisterMode(!registerMode);setError("")}}>{registerMode?"Already have an account? Sign in":"Need an account? Create one"}</button></div></main>;
}
